require("plugins.lsp")
require("plugins.neogen")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.terminal")
require("plugins.nvim-tree")
require("plugins.iron")
require("plugins.buffer")
